"""Create missing base tables (users and materials)

Revision ID: 66dcbc9af747
Revises: da48b564b739
Create Date: 2025-09-18 20:13:57.202733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66dcbc9af747'
down_revision: Union[str, None] = 'da48b564b739'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
