"""Add comprehensive business cost fields to products

Revision ID: eb21e70e1128
Revises: a972eb0855b9
Create Date: 2025-09-28 17:42:21.761004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb21e70e1128'
down_revision: Union[str, None] = 'a972eb0855b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_materials_id', table_name='product_materials')
    op.drop_table('product_materials')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_id', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_products_id', table_name='products')
    op.drop_table('products')
    op.drop_table('proformas')
    op.drop_index('ix_audit_logs_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_materials_id', table_name='materials')
    op.drop_table('materials')
    op.drop_table('proforma_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proforma_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('proforma_id', sa.INTEGER(), nullable=False),
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.INTEGER(), nullable=False),
    sa.Column('precio_unitario', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('subtotal_item', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['proforma_id'], ['proformas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materials',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=False),
    sa.Column('precio_base', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('unidad_base', sa.VARCHAR(), nullable=True),
    sa.Column('precio_unidad_pequena', sa.NUMERIC(precision=12, scale=6), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('deleted_at', sa.DATETIME(), nullable=True),
    sa.Column('version', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_materials_id', 'materials', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('material_id', sa.INTEGER(), nullable=True),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    op.create_table('proformas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('numero_proforma', sa.VARCHAR(), nullable=False),
    sa.Column('tipo_cliente', sa.VARCHAR(), nullable=False),
    sa.Column('cliente_nombre', sa.VARCHAR(), nullable=False),
    sa.Column('cliente_empresa', sa.VARCHAR(), nullable=True),
    sa.Column('cliente_ruc', sa.VARCHAR(), nullable=True),
    sa.Column('cliente_direccion', sa.TEXT(), nullable=True),
    sa.Column('cliente_telefono', sa.VARCHAR(), nullable=True),
    sa.Column('cliente_email', sa.VARCHAR(), nullable=True),
    sa.Column('fecha_emision', sa.DATETIME(), nullable=True),
    sa.Column('fecha_validez', sa.DATETIME(), nullable=False),
    sa.Column('iva_aplicado', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_iva', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('total_final', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_proforma')
    )
    op.create_table('products',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=False),
    sa.Column('iva_percentage', sa.NUMERIC(precision=5, scale=2), nullable=True),
    sa.Column('margen_publico', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('margen_mayorista', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('margen_distribuidor', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('costo_etiqueta', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('costo_envase', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('costo_caja', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('costo_transporte', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('peso_ingredientes_base', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('peso_final_producido', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('peso_empaque', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_products_id', 'products', ['id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=5), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('nombre_empresa', sa.VARCHAR(), nullable=True),
    sa.Column('ruc', sa.VARCHAR(), nullable=True),
    sa.Column('direccion', sa.VARCHAR(), nullable=True),
    sa.Column('telefono', sa.VARCHAR(), nullable=True),
    sa.Column('email_empresa', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('product_materials',
    sa.Column('product_id', sa.INTEGER(), nullable=False),
    sa.Column('material_id', sa.INTEGER(), nullable=False),
    sa.Column('cantidad', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_product_materials_id', 'product_materials', ['id'], unique=False)
    # ### end Alembic commands ###
